GoogleCloudPlatform/golang-docker

base/Dockerfile
This fixes issue #37.
Change-Id: I646a2dc942e77656385c8467fbaec81988704b7b
=> golang-docker: pull go-wrapper from official "golang" Docker base image.

base/Dockerfile
The newest debian images for jessie (gcr.io/google-appengine/debian8:latest) now has all the extra env variables and ca-certs that were in base.
cc @dlorenc
=> Switch base image from base to debian8

base/cloudbuild.yaml.in
this will ensure security updates are picked up in the cloud build.
=> prevent container build from using cached images

test/test_config.yaml
License tests are automated tests to check that all packages installed in the image conform to Google's open source licensing stardards. Check out https://github.com/GoogleCloudPlatform/runtimes-common/tree/master/structure_tests#license-tests for more details.
=> add license tests to structure tests

base/third_party/go-wrapper/go-wrapper
Fallback to running the binary itself if failed to get the application
default credentials.
The corresponding change to the Cloud Debug Agent is at
https://code-review.googlesource.com/c/10431/
=> Debugger degrades more gracefully.

runtime-builder/Dockerfile, runtime-builder/build.sh, runtime-builder/cloudbuild.yaml, runtime-builder/cloudbuild.yaml.in, runtime-builder/go-build.sh
Updated build.sh to take in project ID and also made debian_tag argument
a required parameter.
Updated/fixed comments.
Changed container build invocation to use --substitutions.
Updated build tag to a shorter form.
=> Minor updates to build.

runtime-builder/go-build.sh
Didn't know that "-o" only works with single bracket. This will cause error when deploying not building.
=> Fix error in the go-build script

runtime-builder/build.sh, runtime-builder/go-build.sh
The google_appengine project started not working, changing this to google-appengine fixes the problem.
=> Fix the URL of the appengine debian image

runtime-builder/tests/README.md, runtime-builder/tests/integration/.gitignore, runtime-builder/tests/integration/go-test.yaml, runtime-builder/tests/integration/runtimes.yaml, runtime-builder/tests/integration/test.sh, runtime-builder/tests/integration/test.yaml, runtime-builder/tests/integration/test.yaml.in
This updates the directory structure of the golang integration testing sample application to reflect what's expected in the latest changes to the framework (see https://github.com/GoogleCloudPlatform/runtimes-common/pull/224). The test driver will now look for a `test.yaml.in` (the same way it looks for `Dockerfile.in` when testing runtime base images), substitute in the `STAGING_BUILDER_IMAGE` environment variable into the builder yaml, and use this to deploy the application.
@cybrcodr @shantuo
=> Update build artifacts for integration tests

runtime-builder/tests/deploy_check/app.yaml, runtime-builder/tests/deploy_check/helloworld.go
This is taken from https://github.com/GoogleCloudPlatform/golang-samples, and is used to ensure basic flex deploys work as intended.
@cybrcodr @shantuo
=> Add hello world application for flex deploy check

runtime-builder/tests/README.md, runtime-builder/tests/integration/test.sh, runtime-builder/tests/integration/test.yaml.in
test.yaml.in needs to retain ${_OUTPUT_IMAGE} variable for use by
integration framework.
Updated test.sh also to not rely on envsubst since that does not work on
Macs.
Updated documentation.
=> runtime-builder/tests/integration: fix use of test.yaml.in

runtime-builder/tests/README.md, runtime-builder/tests/integration/test.sh
Update test.sh parameter to take in builder image URL instead of tag.
I find the need to test images in gcp-runtimes as well as ones under my
project or other projects.
=> runtime-builder/tests: update test.sh parameter

runtime-builder/go-build.sh, runtime-builder/tests/integration/src/app/server.go
Add /usr/share/zoneinfo into app image and add custom test to make sure time.LoadLocation works.
=> runtime-builder: add /usr/share/zoneinfo into app image.

runtime-builder/go-build.sh
remove copying of tzdata files since latest distroless/base now contains the package -- https://github.com/GoogleCloudPlatform/distroless/pull/103
=> runtime-builder: remove copying of tzdata files into app image

runtime-builder/go-build.sh
go-app-stager will generate _gopath/main-package-path containing the
relative path of package main from GOPATH if GOPATH is set and main
package files are under GOPATH.
Update go-build.sh to utilize this info in order to reconstruct the main
package directory and build from there.  This should fix issues with
vendor and internal packages along the path that main should have access
to.
=> runtime-builder: update go-build.sh to use _gopath/main-package-path

runtime-builder/tests/integration/src/app/server.go
This should fix the integration tests.
cc @shantuo
=> default to GKE if GAE env vars not found, and remove newlines

runtime-builder/go-1.11.yaml
[`kaniko`](https://github.com/GoogleContainerTools/kaniko) builds container images from a Dockerfile, and enables future improvements to speed up builds by using the image registry as a layer cache (https://github.com/GoogleContainerTools/kaniko/issues/300)
The kaniko builder image is referenced by digest to avoid potential bad kaniko releases, and the tag is included so humans reading the config know what kaniko version is used.
=> Use kaniko to run builds for go 1.11

runtime-builder/go-1.11.yaml
App Engine already resolves tags to digests when these configs are pushed, so hard-coding the digest was unnecessary and loses useful version information.
=> Specify kaniko builder by tag

runtime-builder/Dockerfile, runtime-builder/tests/structure/test_config.yaml
we've switched nearly all of our other maintained language runtime images over to using ubuntu as a base already. this PR will bring the go builder image more in line with the rest of our language images.
=> Switch from debian to ubuntu base in go builder image

runtime-builder/Dockerfile
We're adding version control tools for all go builders so that when the go module proxy fails, it can use git or other tools as a fallback.
=> Adding version control tools as a fall back for go mod proxy

runtime-builder/build.sh
distroless images' latest tag is now a manifest list rather than a single manifest, which causes kaniko heartache.
=> Fix distroless digest tag

runtime-builder/go-1.10.yaml, runtime-builder/go-1.11.yaml, runtime-builder/go-1.12.yaml, runtime-builder/go-1.13.yaml, runtime-builder/go-1.14.yaml, runtime-builder/go-1.15.yaml
This addresses failures reported in https://github.com/GoogleCloudPlatform/golang-samples/issues/1799, later reported to kaniko in https://github.com/GoogleContainerTools/kaniko/issues/1465 by using a newer version of Kaniko that supports multi-arch base images like distroless.
cc @jonjohnsonjr for spotting that these were using such old versions of Kaniko.
=> Upgrade all builders to Kaniko v1.3.0

runtime-builder/build.sh
Flex builds are fine, but Flex deployments using updated builders won't work unless this is updated.
=> Pin to old distroless base digest to satisfy Docker V2 format
